### PR TITLE
unpin mujoco

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
`mujoco-v5` environments require 2.3.3 Minimum

### CODE REVIEW

**Comment by LucasAlegre** [comment]
@ffelten is there a reason we pinned 2.3.2? Can version 2.2.0 break anything?

**Comment by ffelten** [comment]
https://github.com/Farama-Foundation/MO-Gymnasium/issues/39

Here is what I noted down. I guess now we can unpin.

**Comment by ffelten** [comment]
@Kallinteris-Andreas how is the retro compat going if we bump? Can we still use v4?

**Comment by Kallinteris-Andreas** [comment]
yes, https://gymnasium.farama.org/main/environments/mujoco/#versions

**Pull request merged**
